name: wheres-my-family-ios
targets:
  wheres-my-family-ios:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - wheres-my-family-ios
    info:
      path: wheres-my-family-ios/Info.plist
      plist:
        CFBundleIconName: AppIcon
        NSLocationWhenInUseUsageDescription: "This app requires access to your location to share with your family."
        NSLocationAlwaysAndWhenInUseUsageDescription: "This app requires background location access to keep your family updated on your whereabouts."
        UIBackgroundModes:
          - location
    settings:
      DEVELOPMENT_TEAM: LSV2MNUNZ8
      PRODUCT_BUNDLE_IDENTIFIER: ca.sfle.wheresmyfamily
      CODE_SIGN_STYLE: Manual
      CODE_SIGN_IDENTITY: "Apple Distribution"
      MARKETING_VERSION: "2.0.0"
      CURRENT_PROJECT_VERSION: "202"
